// <auto-generated />
namespace LR31_EF_Cars.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OwnerandCarOwnertablesadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OwnerandCarOwnertablesadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201711231807191_Owner and CarOwner tables added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
